version: "3.4"

volumes:
  bucket-data-prod:
  db-data-prod:

networks:
  front:
  back:

services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - sharethis-prod

  sharethis-prod:
    build:
      context: ../sharethis
      dockerfile: Dockerfile
      target: prod-api
    container_name: sharethis-prod-api
    env_file: .env
#    ports:
#      - "8080:8080"
    depends_on:
      - db-prod
      - bucket-prod

  cleaner-prod:
    build:
      context: ../sharethis
      dockerfile: Dockerfile
      target: prod-cleaner
    container_name: sharethis-prod-cleaner
    env_file: .env
    depends_on:
      - db-prod
      - bucket-prod

  bucket-prod:
    image: minio/minio:latest
#    ports:
#      - "9000:9000"
    volumes:
      - bucket-data-prod:/data
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password
    command: server --address 0.0.0.0:9000 --console-address ":9001" /data

  db-prod:
    image: postgres:latest
    volumes:
      - db-data-prod:/var/lib/postgresql/data
#    ports:
#      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 1s
      timeout: 1s
      retries: 10
      start_period: 1s
